config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :pages, only: %i[index home]
  resources :drags do
    resources :bookings, only: %i[new create index edit update]
  end
  resources :bookings, only: [:destroy]
  get "/dashboard", to: "pages#dashboard"
  patch "bookings/:id/accept", to: "bookings#accept", as: :accept
  patch "bookings/:id/decline", to: "bookings#decline", as: :decline
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :drag
  # validates :end_time, comparison: { greater_than: :start_time }
  validates :location, presence: true

end

app/models/doppelg.rb
class Doppelg < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :nickname, presence: true
  validates :city, presence: true
  validates :radius, comparison: { greater_than: 5 }
  validates :specialty, presence: true, inclusion: {
    in: %w[singing, dancing, comedy, acrobatics]
  }
end

app/models/drag.rb
class Drag < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :nickname, presence: true
  validates :city, presence: true
  validates :radius, comparison: { greater_than: 5 }
  validates :specialty, presence: true, inclusion: {
    in: %w[singing dancing comedy doppelganger acrobatics bingo]
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :bookings
  has_one :drag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  def configure_permitted_parameters
    attributes = [:first_name, :last_name]
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @drag = Drag.find(params[:drag_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @drag = Drag.find(params[:drag_id])
    @booking = Booking.new(params_booking)
    @booking.drag = @drag
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index #Dashboard?
    @booking.user = current_user
    @bookings = Booking.find(user_id: @booking.user)
    @bookings = policy_scope(Booking)
  end

  def edit
    @booking = Booking.find(params[:id])
    @drag = @booking.drag
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(params_booking)
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status:'accepted')
    redirect_to dashboard_path
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status:'declined')
    redirect_to dashboard_path
  end

  private

  def params_booking
    params.require(:booking).permit(:booking_date, :start_time, :end_time, :location, :status)
  end
end

app/controllers/doppelgs_controller.rb
class DoppelgsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/drags_controller.rb
class DragsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def new
    @drag = Drag.new
    # skip_authorization
    authorize @drag
  end

  def create
    @drag = Drag.new(params_drag)
    @drag.user = current_user
    authorize @drag
    if @drag.save
      redirect_to drag_path(@drag)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @drags = policy_scope(Drag)
    if params[:location].present? && params[:specialty].present?
      @drags = Drag.where(city: params[:location], specialty: params[:specialty])
    elsif params[:location].present?
      @drags = Drag.where(city: params[:location])
    elsif params[:specialty].present?
      @drags = Drag.where(specialty: params[:specialty])
    else
      @drags = Drag.all
    end
  end

  def show
    @drag = Drag.find(params[:id])
    @booking = Booking.new
    authorize @drag
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def params_drag
    params.require(:drag).permit(:nickname, :city, :radius, :description, :specialty, :hourly_rate, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    #If user is not a drag
    @user_bookings = current_user.bookings

    @drag_bookings = current_user.drag&.bookings

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container form row new-booking-form">
  <h1 id="form-title" >New booking</h1>
  <%= simple_form_for [drag, booking], class:"justify-content-center",
                       html: {
                        data: {
                          controller: 'flatpickr'
                      }
                    } do |f| %>
  <div class="col-8 mx-auto">
      <%= f.input :booking_date,
                  as: :string,
                  input_html: {
                    data: {
                      flatpickr_target: 'bookingDateInput',
  } } %>
  </div>

  <div class="d-flex col-8 mx-auto justify-content-between">
  <div class="col-5">

    <%= f.input :start_time,
                as: :string,
                input_html: {
                  data: {
                    flatpickr_target: 'startTimeInput',
} } %>
  </div>
  <div class="col-5">

    <%= f.input :end_time,
                as: :string,
                input_html: {
                  data: {
                    flatpickr_target: 'endTimeInput',
} } %>

  </div>
  </div>

  <div class="col-8 mx-auto">

    <%= f.input :location %>

  </div>
    <%= f.submit "Book now", class: "button mx-auto" %>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<div class="container form">
  <h1>Modify booking</h1>
  <%= simple_form_for [@drag, @booking] do |f| %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :location %>
    <%= f.submit "Update booking", class: "button" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
  <%= render "form", drag: @drag, booking: @booking%>

app/views/drags/destroy.html.erb
<h1>Doppelgs#destroy</h1>
<p>Find me in app/views/doppelgs/destroy.html.erb</p>

app/views/drags/edit.html.erb
<h1>Doppelgs#edit</h1>
<p>Find me in app/views/doppelgs/edit.html.erb</p>

app/views/drags/index.html.erb
<div class="container mt-5">
  <div class="cards">
    <% @drags.each do |drag| %>
      <%= link_to drag_path(drag), class: "link-to-div" do %>
        <div class="card">
            <%= cl_image_tag drag.photo.key, class: "card-img" %>
            <div class="card-body">
              <div class=specialty-tag-index> <%= drag.specialty %></div>
              <div class="card-body-top">
                <h5 class="card-title"><%= drag.nickname%></h5>
                <h6 class="card-price"><%= drag.hourly_rate %>€ per hour</h5>
              </div>
              <div>
                <p id="card-text">Accepts events <%= drag.radius %> km around <strong><%= drag.city %></strong></p>
              </div>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/drags/new.html.erb
<div class="container form">
  <h1>New drag</h1>
  <%= simple_form_for [@drag] do |f| %>
    <%= f.input :nickname %>
    <%= f.input :photo, as: :file %>
    <%= f.input :city %>
    <%= f.input :radius %>
    <%= f.input :description %>
    <%= f.input :specialty, :collection => %w[singing dancing comedy doppelganger acrobatics] %>
    <%= f.input :hourly_rate %>
    <%= f.submit "Create your drag profile", class: "button" %>
  <% end %>
</div>

app/views/drags/show.html.erb
<div class="d-flex">
  <div>
    <%= cl_image_tag @drag.photo.key, class: "show-img" %>
  </div>
  <div class="flex-grow div-text-section container">
    <h1><%= @drag.nickname %></h1>
    <div class="d-flex">
      <div class="specialty-tag d-flex"><%= @drag.specialty %></div>
      <div class="specialty-tag"><%= @drag.hourly_rate %>€ <em>per hour</em></div>
      <div class="specialty-tag"><%= @drag.city %> <em>(around <%= @drag.radius %>km)</em></div>
    </div>
    <p><%= @drag.description %></p>
  <%# <%= link_to 'Book now', new_drag_booking_path(@drag), class: "button w-50 mx-auto"%>
  <%= render "bookings/form", drag: @drag, booking: @booking%>
  </div>
</div>

app/views/drags/update.html.erb
<h1>Doppelgs#update</h1>
<p>Find me in app/views/doppelgs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doppelganger</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
      <%# #render 'shared/flashes' %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/components/_banner.html.erb
<div class="banner">
  <div class="banner-components container">
    <div class="info">
      <h1>Find the best drag queens for your private events</h1>
      <%= link_to 'DISCOVER', drags_path, class: "button"%>
    </div>
    <div class="banner-img">
      <%= image_tag "03.23_RPDR7603-removebg-preview.png"%>
    </div>
  </div>
</div>

app/views/layouts/components/_card-grid.html.erb
<div class="container">
  <div class="cards">
    <div class="card" style="width: 25rem;">
      <%= image_tag "dn3LsLUG_400x400.jpeg", :class => "card-img"%>
      <div class="card-body">
        <div class="card-body-top">
          <h5 class="card-title">Card title</h5>
          <h6 class="card-price">100€/hour</h5>
        </div>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </div>
    <div class="card" style="width: 25rem;">
      <%= image_tag "62a993f745ad1_03-23-rpdr7098.jpeg", :class => "card-img"%>
      <div class="card-body">
        <div class="card-body-top">
          <h5 class="card-title">Card title</h5>
          <h6 class="card-price">100€/hour</h5>
        </div>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
    </div>
    <div class="card" style="width: 25rem;">
      <%= image_tag "RuPaul_by_David_Shankbone_cropped.jpeg", :class => "card-img"%>
      <div class="card-body">
        <div class="card-body-top">
          <h5 class="card-title">Card title</h5>
          <h6 class="card-price">100€/hour</h5>
        </div>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
  </div>
</div>

app/views/layouts/components/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/components/_searchbar.erb
<div class="search-card">
  <%= form_with url: drags_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :location,
      params[:location],
      class: "search-card",
      placeholder: "Location of your event"
    %>
    <%= select_tag :specialty,
      options_for_select(%w[singing dancing comedy doppelganger acrobatics bingo], params[:specialty]), include_blank: "Choose specialty", #multiple: true,
      class: "form-control search-card",
      placeholder: "Choose specialty"
      %>
    <%= submit_tag "Go", class: "button-round" %>
  <% end %>
</div>

app/views/pages/_drag-booking-card.html.erb
<div class="booking-cards">
  <% @drag_bookings.each do |drag_booking| %>
    <div class="drag-booking-card">
      <div class="booking-logo">
        <i class="fa-solid fa-crown"></i>
      </div>
      <div class="booking-info">
        <h5>Booking on <%= drag_booking.booking_date %> </h5>
        <div class="booking-details">
          <p>with <%= drag_booking.user.first_name %> <%= drag_booking.user.last_name %></p>
          <p>From <%= drag_booking.start_time %> to <%= drag_booking.end_time %></p>
        </div>
        <p>
          <i class="fa-solid fa-location-pin"></i><%= drag_booking.location %>
        </p>
        <p>
          <i class="fa-solid fa-credit-card"></i><%= (drag_booking.end_time[0..1].to_i - drag_booking.start_time[0..1].to_i) * drag_booking.drag.hourly_rate %>€
        </p>
      </div>
      <div class="booking-actions">
          <p><%= drag_booking.status %></p>
          <div class="d-flex justify-content-evenly">
             <%= link_to accept_path(drag_booking), data: {turbo_method: :patch}, class: "text-decoration-none" do %>
              <i class="fa-solid fa-check"></i>
            <% end %>
            <%= link_to decline_path(drag_booking), data: {turbo_method: :patch} do %>
              <i class="fa-solid fa-xmark"></i>
            <% end %>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_user-booking-card.html.erb
<div class="booking-cards">
  <% @user_bookings.each do |user_booking| %>
    <div class="drag-booking-card">
      <div>
        <%= cl_image_tag user_booking.drag.photo.key, class: "booking-photo" %>
      </div>
      <div class="booking-info">
        <h5>Booking on <%= user_booking.booking_date %> </h5>
        <div class="booking-details">
          <p>with <%= user_booking.drag.nickname %></p>
          <p>From <%= user_booking.start_time %> to <%= user_booking.end_time %></p>
        </div>
        <p>
          <i class="fa-solid fa-location-pin"></i><%= user_booking.location %>
        </p>
        <p>
          <i class="fa-solid fa-credit-card"></i><%= (user_booking.end_time[0..1].to_i - user_booking.start_time[0..1].to_i) * user_booking.drag.hourly_rate %>€
        </p>
      </div>
      <div class="booking-actions">
          <p><%= user_booking.status %></p>
          <div class="d-flex justify-content-evenly">
            <%= link_to edit_drag_booking_path(user_booking.drag, user_booking), class: "text-decoration-none" do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <%= link_to booking_path(user_booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure"}, class: "text-decoration-none" do %>
              <i class="fa-solid fa-ban"></i>
            <% end %>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <% if @drag_bookings.nil? %>
    <h2>My bookings</h2>
    <%= render "user-booking-card"%>
  <% else %>
    <h2>My future performances</h2>
    <%= render "drag-booking-card"%>
    <h2>My bookings</h2>
    <%= render "user-booking-card"%>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="background">
  <%= render "layouts/components/banner"%>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by HYMN
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="row mx-0 container-fluid">
    <div class="col-4">
      <%= link_to root_path do %>
        <img src="https://www.coolgenerator.com/Data/Textdesign/202303/21d4fe29bb462fe65028da7882faa8b0.png" />
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="col-4">
      <%# <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
        <div class="search-form-control form-group">
          <input class="form-control string required mx-auto" type="text" name="search[query]" id="search_query" />
          <button name="button" type="submit" class="btn btn-ghost">
            <i class="fas fa-search"></i> Find your drag queen
          </button> %>
             <%= render "layouts/components/searchbar"%>
          <%# <div class="d-flex search-button">
            <i class="fas fa-search"></i>
            <p>Find your drag queen</p>
          </div> %>
        <%# </div>
      </form> %>
    </div>


    <div class="col-4 d-flex justify-content-end">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
            <%= link_to 'My Bookings', dashboard_path ,class: "nav-link"%>
            </li>
            <li class="nav-item active">
              <%= link_to 'Post your Drag profile', new_drag_path(@drag), class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%# <a class="nav-link" href="#">Messages</a> %>
            </li>
            <li class="nav-item dropdown">
            <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, class: "nav-link btn btn-flat ms-4", data:{turbo_method: :delete} %>
            <% else %>
            <%= link_to 'Login', new_user_session_path, class: "nav-link btn btn-flat ms-4" %>
            <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
              </div>
            </li>
            <!--li class="nav-item"-->
            <!--/li-->
        </ul>
      </div>
    </div>
  </div>
</div>